apiVersion: apps/v1
kind: Deployment
metadata:
    name: random-number-deployment
    namespace: random
spec:
    replicas: 2
    selector:
        matchLabels:
            app: random-number
    template:
        metadata:
            name: random-number-pod
            labels:
                app: random-number
        spec:
            containers:
            - name: random-number-container
              image: kulyndar/random:number
              resources:
                requests:
                    cpu: "250m"
                    memory: "128M"
                limits:
                    cpu: "500m"
                    memory: "256M"
              livenessProbe:
                httpGet:
                    path: /random-number/health
                    port: 8082
                initialDelaySeconds: 3
                periodSeconds: 10
                failureThreshold: 3
              readinessProbe:
                httpGet:
                    path: /random-number/health
                    port: 8082
                initialDelaySeconds: 0
                periodSeconds: 2
              env:
              - name: randomservice.name.address
                value: http://random-name-service.random/random-name
              ports:
              - containerPort: 8082