apiVersion: v1
kind: Service
metadata:
    name: random-name-service
    namespace: random
spec:
    selector: 
        app: random-name
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
    