apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: migration-binding
subjects:
- kind: ServiceAccount
  name: migration # Name is case sensitive
  namespace: default
- kind: User
  name: system:bootstrap:07401b # Name is case sensitive
roleRef:
  kind: ClusterRole
  name: migration
  apiGroup: rbac.authorization.k8s.io