apiVersion: apps/v1
kind: Deployment
metadata:
    name: random-name-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: random-name
    template:
        metadata:
            name: random-name-pod
            labels:
                app: random-name
        spec:
            containers:
            - name: random-name-container
              image: random/random-name
              imagePullPolicy: Never
              ports:
              - containerPort: 8081