apiVersion: v1
kind: Service
metadata:
    name: random-number-service
spec:
    selector: 
        app: random-number
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
    