apiVersion: apps/v1
kind: Deployment
metadata:
    name: random-number-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: random-number
    template:
        metadata:
            name: random-number-pod
            labels:
                app: random-number
        spec:
            containers:
            - name: random-number-container
              image: random/random-number
              imagePullPolicy: Never
              env:
              - name: randomservice.name.address
                value: http://random-name-service.default.svc.cluster.local/random-name
#                value: http://10.97.233.67:80/random-name
              ports:
              - containerPort: 8082